

#ifndef PAVEL
               <mass>0.039</mass>
                <inertia>
                    <ixx>4.78233711e+00</ixx>
                    <ixy>2.06443170e-09</ixy>
                    <ixz>3.14256508e-00</ixz>
                    <iyy>4.78233728e+00</iyy>
                    <iyz>1.83990112e-08</iyz>
                    <izz>2.44284722e-01</izz>
                </inertia>


#else
        <!--actual mass <mass>0.032</mass> -->
        <mass>0.32</mass>
        <inertia>
          <!-- actual inertia
          <ixx>0.000009</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.000009</iyy>
          <iyz>0</iyz>
          <izz>0.000016</izz>-->

          <ixx>0.00009</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.00009</iyy>
          <iyz>0</iyz>
          <izz>0.00016</izz>
        </inertia>
#endif
