

#ifndef PAVEL
                <mass>12</mass>
                <inertia>
                    <ixx>1</ixx>
                    <ixy>0</ixy>
                    <ixz>0</ixz>
                    <iyy>1</iyy>
                    <iyz>0</iyz>
                    <izz>1</izz>
                </inertia>
                
 #else             
                
                <mass>0.1</mass>
                <inertia>
                    <ixx>.1</ixx>
                    <ixy>0</ixy>
                    <ixz>0</ixz>
                    <iyy>.1</iyy>
                    <iyz>0</iyz>
                    <izz>.1</izz>
                </inertia>
 #endif               
