# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - fanuc_joint_1
    - fanuc_joint_2
    - fanuc_joint_3
    - fanuc_joint_4
    - fanuc_joint_5
    - fanuc_joint_6
    - fanuc_prism1
    - fanuc_prism2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - fanuc_joint_1
      - fanuc_joint_2
      - fanuc_joint_3
      - fanuc_joint_4
      - fanuc_joint_5
      - fanuc_joint_6
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - fanuc_prism1
      - fanuc_prism2
