joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

joint_1_controller:
  type: "position_controllers/JointPositionController"
  joint: fanuc_joint_1
  pid: {p: 100.0, i: 0.5, d: 10.0}

joint_2_controller:
  type: "position_controllers/JointPositionController"
  joint: fanuc_joint_2
  pid: {p: 100.0, i: 0.5, d: 10.0}

joint_3_controller:
  type: "position_controllers/JointPositionController"
  joint: fanuc_joint_3
  pid: {p: 100.0, i: 0.5, d: 10.0}

joint_4_controller:
  type: "position_controllers/JointPositionController"
  joint: fanuc_joint_4
  pid: {p: 100.0, i: 0.5, d: 10.0}

joint_5_controller:
  type: "position_controllers/JointPositionController"
  joint: fanuc_joint_5
  pid: {p: 100.0, i: 0.5, d: 10.0}

joint_6_controller:
  type: "position_controllers/JointPositionController"
  joint: fanuc_joint_6
  pid: {p: 100.0, i: 0.5, d: 10.0}
