# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  fanuc_joint_1:
    min_posiiton: -1.5707963267948966192313216916398
    max_posiiton: 1.5707963267948966192313216916398
    has_velocity_limits: true
    max_velocity: 7.85
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_joint_2:
    has_velocity_limits: true
    max_velocity: 6.63
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_joint_3:
    has_velocity_limits: true
    max_velocity: 9.08
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_joint_4:
    min_posiiton: -1.5707963267948966192313216916398
    max_posiiton: 1.5707963267948966192313216916398
    has_velocity_limits: true
    max_velocity: 9.6
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_joint_5:
    has_velocity_limits: true
    max_velocity: 9.51
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_joint_6:
    has_velocity_limits: true
    max_velocity: 17.45
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_prism1:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  fanuc_prism2:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
